name: Build and Deploy MkDocs

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest version of Python 3

      - name: Install MkDocs and Material theme
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-same-dir

      - name: Build MkDocs site
        run: mkdocs build --config-file .mkdocs/mkdocs.yml --verbose --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./site
          # Uncomment the following line if you are deploying to a custom domain
          # cname: 'your-custom-domain.com'

